// Shared styles for chat components

export const chatStyles = {
  container: {
    display: "flex",
    height: "calc(100vh - 60px)",
    fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
  },
  sidebar: {
    width: "300px",
    borderRight: "1px solid #e2e8f0",
    backgroundColor: "#f8fafc",
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  sidebarTabs: {
    display: "flex",
    borderBottom: "1px solid #e2e8f0",
    backgroundColor: "#fff",
  },
  sidebarTab: {
    flex: 1,
    padding: "12px 16px",
    border: "none",
    backgroundColor: "transparent",
    fontSize: "13px",
    fontWeight: 500,
    cursor: "pointer",
    color: "#64748b",
    borderBottom: "2px solid transparent",
    transition: "all 0.15s ease",
  },
  sidebarTabActive: {
    color: "#3b82f6",
    borderBottomColor: "#3b82f6",
    backgroundColor: "#f8fafc",
  },
  sidebarHeader: {
    padding: "12px 16px",
    borderBottom: "1px solid #e2e8f0",
    backgroundColor: "#fff",
  },
  sidebarContent: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "12px",
  },
  skillItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    padding: "10px 12px",
    marginBottom: "8px",
    backgroundColor: "#fff",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  skillItemSelected: {
    backgroundColor: "#eff6ff",
    borderColor: "#3b82f6",
  },
  chatArea: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    backgroundColor: "#fff",
  },
  chatHeader: {
    padding: "16px 24px",
    borderBottom: "1px solid #e2e8f0",
    backgroundColor: "#fff",
  },
  messagesContainer: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "24px",
  },
  messageWrapper: {
    marginBottom: "20px",
    display: "flex",
    flexDirection: "column" as const,
  },
  userMessage: {
    alignSelf: "flex-end",
    maxWidth: "70%",
    padding: "12px 16px",
    backgroundColor: "#3b82f6",
    color: "#fff",
    borderRadius: "16px 16px 4px 16px",
  },
  assistantMessage: {
    alignSelf: "flex-start",
    maxWidth: "80%",
    padding: "12px 16px",
    backgroundColor: "#f1f5f9",
    color: "#1e293b",
    borderRadius: "16px 16px 16px 4px",
  },
  inputArea: {
    padding: "16px 24px",
    borderTop: "1px solid #e2e8f0",
    backgroundColor: "#fff",
  },
  inputWrapper: {
    display: "flex",
    gap: "12px",
    alignItems: "flex-end",
  },
  textarea: {
    flex: 1,
    padding: "12px 16px",
    border: "1px solid #cbd5e1",
    borderRadius: "12px",
    fontSize: "15px",
    resize: "none" as const,
    minHeight: "48px",
    maxHeight: "150px",
    fontFamily: "inherit",
  },
  sendButton: {
    padding: "12px 24px",
    backgroundColor: "#3b82f6",
    color: "#fff",
    border: "none",
    borderRadius: "12px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "background-color 0.15s ease",
  },
  skillsUsedBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    padding: "4px 8px",
    backgroundColor: "#dbeafe",
    color: "#1d4ed8",
    borderRadius: "4px",
    fontSize: "11px",
    fontWeight: 500,
    marginTop: "8px",
    marginRight: "4px",
  },
  emptyState: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    color: "#64748b",
    textAlign: "center" as const,
    padding: "40px",
  },
  tag: {
    display: "inline-block",
    padding: "2px 6px",
    backgroundColor: "#e2e8f0",
    color: "#64748b",
    borderRadius: "4px",
    fontSize: "10px",
    marginRight: "4px",
    marginTop: "4px",
  },
  promptItem: {
    padding: "10px 12px",
    marginBottom: "8px",
    backgroundColor: "#fff",
    borderRadius: "8px",
    border: "1px solid #e2e8f0",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  promptCategory: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "10px",
    fontWeight: 600,
    marginBottom: "6px",
  },
};

// Button styles
export const buttonStyles = {
  small: {
    padding: "4px 8px",
    fontSize: "11px",
    backgroundColor: "#f1f5f9",
    border: "1px solid #e2e8f0",
    borderRadius: "4px",
    cursor: "pointer",
  },
  primary: {
    padding: "8px 16px",
    fontSize: "13px",
    backgroundColor: "#3b82f6",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    fontWeight: 500,
    cursor: "pointer",
  },
  success: {
    padding: "8px 16px",
    fontSize: "13px",
    backgroundColor: "#22c55e",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    fontWeight: 500,
    cursor: "pointer",
  },
  outline: {
    padding: "8px 16px",
    fontSize: "13px",
    backgroundColor: "transparent",
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    cursor: "pointer",
  },
};
