name: Deploy to AWS Amplify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Note: Amplify has built-in CI/CD that automatically deploys on push
# This workflow is optional and can be used for:
# - Pre-deployment checks
# - Running tests
# - Database migrations
# - Custom deployment logic

env:
  AWS_REGION: us-east-1
  AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  pre-deploy-checks:
    name: Pre-deployment checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run linting
        run: npm run lint
        continue-on-error: true

      - name: Run type checking
        run: npx tsc --noEmit
        continue-on-error: true

      - name: Run tests
        run: npm test
        continue-on-error: true

  database-migration:
    name: Run database migrations
    runs-on: ubuntu-latest
    needs: pre-deploy-checks
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get DATABASE_URL from Parameter Store
        id: get-db-url
        run: |
          DB_URL=$(aws ssm get-parameter \
            --name "/amplify/${{ env.AMPLIFY_APP_ID }}/main/DATABASE_URL" \
            --with-decryption \
            --query 'Parameter.Value' \
            --output text)
          echo "::add-mask::$DB_URL"
          echo "DATABASE_URL=$DB_URL" >> $GITHUB_ENV

      - name: Run Prisma migrations
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          npx prisma migrate deploy

      - name: Generate Prisma client
        run: npx prisma generate

  notify-deployment:
    name: Notify deployment status
    runs-on: ubuntu-latest
    needs: [pre-deploy-checks, database-migration]
    if: always() && github.ref == 'refs/heads/main'

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Amplify deployment status
        id: amplify-status
        run: |
          # Get latest job for main branch
          JOB_ID=$(aws amplify list-jobs \
            --app-id ${{ env.AMPLIFY_APP_ID }} \
            --branch-name main \
            --max-results 1 \
            --query 'jobSummaries[0].jobId' \
            --output text)

          STATUS=$(aws amplify get-job \
            --app-id ${{ env.AMPLIFY_APP_ID }} \
            --branch-name main \
            --job-id $JOB_ID \
            --query 'job.summary.status' \
            --output text)

          echo "status=$STATUS" >> $GITHUB_OUTPUT
          echo "Amplify deployment status: $STATUS"

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Pre-deployment checks passed! Amplify will automatically deploy this PR.'
            })
