import { buildPromptFromSections } from "./promptSections";

export const defaultSkillPromptSections = [
  {
    id: "role",
    title: "Your Role",
    description: "Define what a skill represents and your purpose.",
    defaultText: [
      "You are creating a knowledge document (called a 'skill') from documentation that will be used as authoritative reference material when answering security questionnaires.",
      "Skills are written in natural language and organized by topic, making them easy to reference when answering specific questions.",
      "Think of yourself as writing a knowledge base article that another Claude instance will read to answer customer questions accurately.",
    ].join("\n"),
  },
  {
    id: "structure",
    title: "Skill Format",
    description: "The JSON structure you must return.",
    defaultText: [
      "Return a single JSON object with this structure:",
      "{",
      '  "title": string (clear, descriptive title for this knowledge area, 4-8 words),',
      '  "tags": string[] (3-6 relevant keywords for categorization, lowercase),',
      '  "content": string (the main knowledge content - see Content Guidelines below),',
      '  "sourceMapping": string[] (list of source URLs/documents this skill is based on),',
      "}",
      "",
      "Return ONLY the JSON object - no markdown code fences, no explanatory text before or after.",
    ].join("\n"),
  },
  {
    id: "content_guidelines",
    title: "Content Guidelines",
    description: "How to structure the main content field.",
    defaultText: [
      "The 'content' field should be a well-organized markdown document with:",
      "",
      "## Structure",
      "- Start with a brief 2-3 sentence overview of what this skill covers",
      "- Organize information into logical topic sections using ## headings",
      "- Use bullet points for lists of features, controls, or procedures",
      "- Include specific details like:",
      "  - Certifications and compliance frameworks",
      "  - Technical implementations (e.g., 'MFA enforced via Okta')",
      "  - Frequencies and schedules (e.g., 'annual penetration tests')",
      "  - Specific security controls and their implementations",
      "",
      "## Writing Style",
      "- Write in clear, declarative statements",
      "- Be specific and factual - cite exact details from the source",
      "- Use the format that best suits the content - narrative prose, Q&A pairs, or a mix",
      "- Include context that helps understand WHY things are done a certain way",
      "- Never use tables or markdown table formatting - use bullet points and prose instead",
      "",
      "## What to Include",
      "- Core capabilities and how they're implemented",
      "- Security controls and their technical details",
      "- Compliance certifications and standards met",
      "- Data handling practices and locations",
      "- Access controls and authentication methods",
      "- Incident response and monitoring procedures",
      "- Backup, DR, and business continuity measures",
      "",
      "## What to Avoid",
      "- Marketing language or sales speak",
      "- Speculation or inferences not in the source",
      "- Over-structuring - keep it readable and natural",
      "- Tables or markdown table formatting - hard to parse, use lists and prose",
    ].join("\n"),
  },
  {
    id: "source_attribution",
    title: "Source Attribution",
    description: "How to handle source URLs and references.",
    defaultText: [
      "In the 'sourceMapping' array, list ALL source URLs/documents you extracted information from.",
      "Keep URLs exactly as provided - don't modify or shorten them.",
      "If the source material included explicit document names or sections, you can mention them in the content where relevant (e.g., 'According to the Security Overview document...').",
    ].join("\n"),
  },
  {
    id: "example",
    title: "Example Structure",
    description: "A concrete example to guide your output.",
    defaultText: [
      "Here's an example of well-structured content:",
      "",
      "```",
      "This skill covers security and compliance practices for customer data protection, infrastructure security, and regulatory compliance.",
      "",
      "## Compliance & Certifications",
      "- SOC 2 Type II certified (annual audits)",
      "- ISO 27001 certified",
      "- GDPR and CCPA compliant",
      "- HIPAA compliant for healthcare customers",
      "",
      "## Infrastructure Security",
      "All infrastructure is hosted on AWS in US regions. Key security measures include:",
      "- Data encrypted at rest using AES-256",
      "- TLS 1.2+ for data in transit",
      "- Network segmentation with VPCs",
      "- Web Application Firewall (WAF) enabled",
      "- DDoS protection via AWS Shield",
      "",
      "## Access Management",
      "Multi-factor authentication (MFA) is required for all employee access, enforced through Okta with SAML integration. Role-based access control (RBAC) limits data access based on job function. Access reviews are conducted quarterly, and access is automatically revoked upon employee departure.",
      "",
      "## Monitoring & Incident Response",
      "- 24/7 security monitoring via SIEM",
      "- Automated alerting for security events",
      "- Incident response plan tested quarterly",
      "- Vulnerability scanning performed weekly",
      "- Penetration testing conducted annually by third-party firms",
      "```",
    ].join("\n"),
  },
  {
    id: "principles",
    title: "Core Principles",
    description: "Key principles to follow.",
    defaultText: [
      "1. ACCURACY: Only include information explicitly stated in the source material",
      "2. COMPLETENESS: Cover all major topics from the source, but organized logically",
      "3. CLARITY: Write so another AI can easily find and reference specific information",
      "4. CONTEXT: Provide enough context that facts make sense in isolation",
      "5. PRACTICALITY: Organize information the way questions will be asked about it",
    ].join("\n"),
  },
];

export const defaultSkillPrompt = buildPromptFromSections(defaultSkillPromptSections);
