// Styles for the Knowledge Library page
export const styles = {
  container: {
    maxWidth: "1100px",
    margin: "0 auto",
    padding: "24px",
  },
  header: {
    marginBottom: "24px",
  },
  title: {
    fontSize: "1.75rem",
    fontWeight: 700,
    marginBottom: "8px",
  },
  subtitle: {
    color: "#64748b",
    fontSize: "0.95rem",
  },
  tabBar: {
    display: "flex",
    gap: "4px",
    borderBottom: "1px solid #e2e8f0",
    marginBottom: "24px",
  },
  tab: {
    padding: "12px 20px",
    border: "none",
    background: "transparent",
    fontSize: "0.95rem",
    fontWeight: 500,
    color: "#64748b",
    cursor: "pointer",
    borderBottom: "2px solid transparent",
    marginBottom: "-1px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  tabActive: {
    color: "#0ea5e9",
    borderBottomColor: "#0ea5e9",
    fontWeight: 600,
  },
  tabCount: {
    backgroundColor: "#f1f5f9",
    padding: "2px 8px",
    borderRadius: "10px",
    fontSize: "0.8rem",
  },
  tabCountActive: {
    backgroundColor: "#e0f2fe",
    color: "#0369a1",
  },
  controls: {
    display: "flex",
    gap: "12px",
    marginBottom: "20px",
    flexWrap: "wrap" as const,
    alignItems: "center",
  },
  searchBox: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 14px",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
    backgroundColor: "#fff",
    flex: 1,
    minWidth: "250px",
    maxWidth: "400px",
  },
  searchInput: {
    border: "none",
    outline: "none",
    flex: 1,
    fontSize: "0.95rem",
  },
  filterButton: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    padding: "10px 14px",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
    backgroundColor: "#fff",
    cursor: "pointer",
    fontSize: "0.9rem",
    color: "#475569",
  },
  filterButtonActive: {
    borderColor: "#0ea5e9",
    backgroundColor: "#f0f9ff",
    color: "#0369a1",
  },
  categoryDropdown: {
    position: "absolute" as const,
    top: "100%",
    left: 0,
    right: 0,
    marginTop: "4px",
    backgroundColor: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
    zIndex: 50,
    maxHeight: "300px",
    overflowY: "auto" as const,
  },
  categoryOption: {
    padding: "10px 14px",
    cursor: "pointer",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid #f1f5f9",
  },
  card: {
    border: "1px solid #e2e8f0",
    borderRadius: "10px",
    padding: "16px",
    marginBottom: "12px",
    backgroundColor: "#fff",
    transition: "border-color 0.2s",
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "8px",
  },
  cardTitle: {
    fontSize: "1rem",
    fontWeight: 600,
    color: "#1e293b",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  cardDescription: {
    color: "#64748b",
    fontSize: "0.9rem",
    marginBottom: "12px",
    lineHeight: 1.5,
  },
  cardMeta: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "8px",
    alignItems: "center",
  },
  pill: {
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: "999px",
    fontSize: "0.75rem",
    fontWeight: 500,
    backgroundColor: "#e0f2fe",
    color: "#0369a1",
  },
  typeBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    padding: "3px 8px",
    borderRadius: "4px",
    fontSize: "0.7rem",
    fontWeight: 600,
    textTransform: "uppercase" as const,
  },
  typeBadgeSkill: {
    backgroundColor: "#dcfce7",
    color: "#166534",
  },
  typeBadgeDoc: {
    backgroundColor: "#fef3c7",
    color: "#92400e",
  },
  typeBadgeUrl: {
    backgroundColor: "#e0e7ff",
    color: "#3730a3",
  },
  typeBadgeCustomer: {
    backgroundColor: "#fce7f3",
    color: "#be185d",
  },
  emptyState: {
    padding: "60px 20px",
    textAlign: "center" as const,
    backgroundColor: "#f8fafc",
    borderRadius: "12px",
    border: "1px dashed #cbd5e1",
  },
  deleteButton: {
    padding: "6px",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    color: "#94a3b8",
    borderRadius: "4px",
    transition: "color 0.2s",
  },
  urlLink: {
    color: "#0ea5e9",
    fontSize: "0.85rem",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    textDecoration: "none",
  },
  analysisPanel: {
    padding: "16px",
    backgroundColor: "#faf5ff",
    border: "1px solid #c4b5fd",
    borderRadius: "10px",
    marginBottom: "24px",
  },
  expandButton: {
    padding: "4px 8px",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    color: "#64748b",
    fontSize: "0.85rem",
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  expandedContent: {
    marginTop: "12px",
    padding: "12px",
    backgroundColor: "#f8fafc",
    borderRadius: "6px",
    fontSize: "0.9rem",
    lineHeight: 1.6,
  },
};
